Repository Rreyth/get-transcended, pull requests merged in 2024-04, with the labels that each got.

#45 fix #35 with sleep 1
  srcs/requirements/Django/utils/start.sh
Labels: bug

#51 [Issue-44]: redo dockers
  srcs/docker-compose.yml
  srcs/requirements/Daphne/Dockerfile
  srcs/requirements/Daphne/utils/requirements
  srcs/requirements/Django/Dockerfile
  srcs/requirements/Django/utils/requirements
  srcs/requirements/Nginx/Dockerfile
  srcs/requirements/Nginx/conf/nginxTranscend.conf
  srcs/requirements/Postgres/Dockerfile
Labels: enhancement, Backend

#52 add tzdata package for django && daphne
  srcs/requirements/Daphne/utils/requirements
  srcs/requirements/Django/utils/requirements
Labels: bug

#59 add docker adminer
  srcs/docker-compose.yml
Labels: enhancement, Database
